version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_AWS
    container_name: cdo_app
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - DB_PATH=/data/users.db
      - TZ=America/Bogota
      # Supabase connection (optional if using SQLite)
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_DB=${SUPABASE_DB}
      - SUPABASE_PORT=${SUPABASE_PORT}
    volumes:
      - ./data:/data
    restart: always

  fevrips-api:
    image: fevripsacr.azurecr.io/minsalud.fevrips.apilocal:latest
    container_name: fevrips-api
    ports:
      - "9443:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fevrips2024*
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificates/server.pfx
    volumes:
      - ./certificates:/certificates
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile_AWS
    container_name: cdo_api
    command: uvicorn src.server_api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/data/users.db
      - TZ=America/Bogota
      # Supabase connection (optional if using SQLite)
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_DB=${SUPABASE_DB}
      - SUPABASE_PORT=${SUPABASE_PORT}
    volumes:
      - ./data:/data
    restart: always
