version: '3.4'
services:
  fevrips-api:
    image: fevripsacr.azurecr.io/minsalud.fevrips.apilocal:latest
    container_name: fevrips-api
    ports:
      - "9443:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fevrips2024*
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificates/server.pfx
    volumes:
      # AWS/Linux friendly volume mapping
      # Ensure 'certificates' folder exists in the same directory as docker-compose.yml
      # and contains 'server.pfx'
      - ./certificates:/certificates
    restart: always
